version: '3.8'

services:
  redis:
    image: redis:7.4.5-alpine
    container_name: redis-prod
    restart: unless-stopped
    env_file: .env
    volumes:
      - redis_data:/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:16.9-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    env_file: .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 3

  spot-fetch-price:
    build: ./spot-fetch-price
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - internal_network
    ports:
      - "8080:8080"

  web-ui:
    build: ./web-ui
    networks:
      - public_network
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  telegram-notifier:
    build: ./telegram-notifier
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - internal_network
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  pg_data:
  rabbitmq_data:

networks:
  internal_network:
    driver: bridge
  public_network:
    driver: bridge
  monitoring_network:
    driver: bridge