services:
  redis:
    image: redis:7.4.5-alpine3.21
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - crypto-net

  postgres:
    image: postgres:16.9
    ports:
      - "${DB_PORT_EXTERNAL:-15432}:${DB_PORT_INTERNAL:-5432}"
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
      POSTGRES_DB: ${DB_NAME:-crypto_bridge_db}
    volumes:
      - "${DB_VOLUME:-/crypto-bridge-db-data}:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - crypto-net

  rabbitmq:
    image: rabbitmq:4.1.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - crypto-net

  spot-fetch-price:
    build: ./spot-fetch-price
    container_name: spot-fetch-price
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - crypto-net

  web-ui:
    build: ./web-ui
    container_name: web-ui
    ports:
      - "80:80"
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge