services:
  redis:
    image: redis:7.4.5-alpine3.21
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge