server:
  port: 8081

spring:
  application:
    name: telegram-notifier
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:pass}
    username: ${DB_USER:admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT_EXTERNAL:15433}/${DB_NAME:telegram_notifier_db}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

arbitrage:
  rabbit:
    queue-name: arbitrage.events
    exchange-name: arbitrage.exchange
    routing-key: arbitrage.opportunity