server:
  port: 8080

spring:
  application:
    name: CryptoBridge
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

exchange:
  cache:
    refresh-ms: 300000

arbitrage:
  scanner:
    refresh-ms: 300000
