spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  data:
    redis:
      timeout: 5000ms
  rabbitmq:
    connection-timeout: 5000
    cache:
      channel.size: 100
      
logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true