server:
  port: 8080

spring:
  application:
    name: spot-fetch-price
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

exchange:
  cache:
    refresh-ms: 300000

arbitrage:
  scanner:
    refresh-ms: 300000

logging:
#  config: spot-fetch-price/src/main/resources/logback-spring.xml
  level:
    org.springframework.web: DEBUG