server:
  port: 8080

spring:
  application:
    name: spot-fetch-price
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:pass}
    username: ${DB_USER:admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT_EXTERNAL:15432}/${DB_NAME:crypto_bridge_db}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

exchange:
  cache:
    refresh-ms: 300000

arbitrage:
  scanner:
    refresh-ms: 300000
  rabbit:
    queue-name: arbitrage.events
    exchange-name: arbitrage.exchange
    routing-key: arbitrage.opportunity

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.reactive.function.client: WARN
    reactor.netty.http.client: WARN
    org.hibernate: warn

exchanger:
  properties:
    kucoin:
      key: ${kucoin.api.key:}
      secret: ${kucoin.api.secret:}
      passphrase: ${kucoin.api.passphrase:}
    bybit:
      key: ${bybit.api.key:}
      secret: ${bybit.api.secret:}
    gateio:
      key: ${gateio.api.key:}
      secret: ${gateio.api.secret:}
    mexc:
      key: ${mexc.api.key:}
      secret: ${mexc.api.secret:}
    bitget:
      key: ${bitget.api.key:}
      secret: ${bitget.api.secret:}
      passphrase: ${bitget.api.passphrase:}
    okx:
      key: ${okx.api.key:}
      secret: ${okx.api.secret:}
      passphrase: ${okx.api.passphrase:}
    bingx:
      key: ${bingx.api.key:}
      secret: ${bingx.api.secret:}