server:
  port: 8080

spring:
  application:
    name: spot-fetch-price
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

exchange:
  cache:
    refresh-ms: 300000

arbitrage:
  scanner:
    refresh-ms: 300000

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.reactive.function.client: WARN
    reactor.netty.http.client: WARN

exchanger:
  properties:
    kucoin:
      key: ${kucoin.api.key:}
      secret: ${kucoin.api.secret:}
      passphrase: ${kucoin.api.passphrase:}
    bybit:
      key: ${bybit.api.key:}
      secret: ${bybit.api.secret:}
    gateio:
      key: ${gateio.api.key:}
      secret: ${gateio.api.secret:}
    mexc:
      key: ${mexc.api.key:}
      secret: ${mexc.api.secret:}
    bitget:
      key: ${bitget.api.key:}
      secret: ${bitget.api.secret:}
      passphrase: ${bitget.api.passphrase:}